stages:
  - unit
  - acceptance

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

phpunit:
  stage: unit
  image: wordpress:5.4.0-php7.3-fpm
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq mariadb-client
    - apt-get install git -yqq # Install git, the php image doesn't have installed
    - apt-get -yqqf install vim wget zip unzip subversion libmcrypt-dev --fix-missing # instll the required packages for the running CI tests.
    - curl -sS https://getcomposer.org/installer | php # Install composer
    - php composer.phar install # Install all project dependencies
  script:
    - vendor/bin/phpunit -c phpunit-ci.xml.dist

JavaScript tests
    stage: unit
    image: node:latest
    script:
      - cd wp-content/plugins/cf-mailchimp
      - yarn
      - npm run test:ci
