version: '3.1'

services:
  codeception:
    build: .
    depends_on:
      - wordpress
    volumes:
      - ./:/project
      - wp-core:/wp-core
    entrypoint: /docker-entrypoint.sh
  wordpress:
    image: wordpress
    ports:
      - 8228:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wp-core:/var/www/html
      - .:/var/www/html/wp-content/plugins/ninja-forms-views
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
  cli:
    image: wordpress:cli
    volumes:
    - wordpress:/var/www/html
    - .:/var/www/html/wp-content/plugins/ninja-forms-views
    - ./wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_PASSWORD: password
      ABSPATH: /usr/src/wordpress/
  mysql:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp
  composer:
    image: composer
    volumes:
      - .:/app
  chrome:
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - '4444'
      - '5900:5900'
volumes:
  testsuite:
  wp-core: